version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["ng","serve","--host","0.0.0.0"]
    ports:
      - "4200:4200"
    volumes:
      - .:/home/app
      - /home/app/node_modules
    