FROM mhart/alpine-node:6.9.1

MAINTAINER Daniel Ha (dha@kla-tencor.com)

RUN apk add --no-cache \
    python \
    python-dev \
    py-pip \
    build-base \
    cairo \
    git \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*


RUN set -ex;                  \
    npm install -g angular-cli; \
    npm cache clean;

#RUN useradd --user-group --create-home --shell /bin/false app
#USER app

ENV NODE_ENV development

RUN mkdir -p /home/app
ENV HOME=/home/app
WORKDIR $HOME

ADD package.json /home/app
RUN npm install --unsafe-perm
# && npm install -no-bin-links

RUN cd $HOME

EXPOSE 4200



